### ISSUE TITLE
New Site on Safari

### ISSUE THREAD

**Issue by matthutson23** [seanfreiburg/unbury.us#18]
The new version of the site no longer works on Safari. The site loads, but then the buttons don't do anything when clicked.

**Comment by willklein** [comment]
I went to investigate this myself and it may be resolved. Everything works for me.

Tested on:
- OS X 10.9.5, Safari 7.1.1
- OS X 10.9.5, Safari 7.1.5
- OS X 10.10.3, Safari 8.0.5

**Comment by seanfreiburg** [comment]
The gods have smiled upon me.
