### ISSUE TITLE
explain what you mean by being financially independent

### ISSUE THREAD

**Issue by SirZach** [seanfreiburg/unbury.us#24]
"25 x spending to be FI."

What math is happening? Maybe adding a graph here would help explain. Also, we all spend differently :)

**Comment by seanfreiburg** [comment]
The safe withdraw rate is 4% of invested assets. 25x what you spend a year is the amount of capital you need to sustain the safe withdrawal. The assumption is if you spending stays the same as now, if you have 25x your yearly spending, it can sustain you forever.

http://www.getrichslowly.org/blog/2014/01/03/the-one-page-guide-to-financial-independence/

**Comment by SirZach** [comment]
I appreciate the quick response! I think your comment here, or some version of it, should make it to the calculator to help explain to others. Thanks!
