### ISSUE TITLE
https cert produces error

### ISSUE THREAD

**Issue by mehmetaergun** [seanfreiburg/unbury.us#26]
unbury.us uses an invalid security certificate. 

    The certificate is only valid for the following names: *.azurewebsites.net, *.scm.azurewebsites.net, *.azure-mobile.net, *.scm.azure-mobile.net 

    (Error code: ssl_error_bad_cert_domain)

**Comment by seanfreiburg** [comment]
Because I don't use https. Its not necessary since no data flows to the server. All state is contained in the URL. It would just create overhead.
